### ISSUE TITLE
Bug: EX-load flags are not correctly reset upon existing character reset.

### ISSUE THREAD

**Issue by Sewer56** [RidersBoulevard/TournamentEdition#23]
**Describe the Bug**

EX-load flags should be reset on leaving Character Select, such that modes which do not have a CSS such as Story or Mission Mode, can correctly run without the flags taking effect.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run the Game
2. Enter Free Race Character Select Screen
3. Toggle an EX-load flag. e.g. by selecting Reala in place of Nights.
4. Exit to menu, and begin a game mode which does not have Character Select Screen
5. ???
6. Profit

**Expected Behavior**
EX-load flags should be correctly reset upon leaving the Character Select screen.

**Screenshots**

https://user-images.githubusercontent.com/6697380/236739856-95448e45-ce82-4416-af5a-f93f5cbbcf6c.mp4

(Video from Boredlism the actual side-effect in action.)

Sonic should not be replaced with Reala.

**Additional Information**

- **Game Version**: 2.2
- **Dolphin Version**: Any
- **Save State**: Not Necessary

**Comment by KidWizardOfTheWeb** [comment]
Fixed in 2.2.2.
Emerald chase may still have the issue only if you ex-load while picking from the CSS in that mode, but will properly be reset if the menu is exited.
