### ISSUE TITLE
Bug: Why have miku when we should be using Goku

### ISSUE THREAD

**Issue by joeatron** [RidersBoulevard/TournamentEdition#24]
**Describe the Bug**
Bug: Miku is in the game

**To Reproduce**

1. Run the Game ROM
2. Select Miku
3. Play
4. See Miku in game and not Goku

**Expected Behavior**
Should be Goku

**Screenshots**
you can see for your self

**Additional Information**

TE 2.3

Please provide a save state if possible.
Feel free to also add any other context about the problem here.

you will never get my save states :)

(posting because I am pretty sure nobody reads these (why are you reading this?)

**Comment by akshayans** [comment]
I'm experiencing this bug as well. It really needs to be fixed, as this is ruining my experience.

**Comment by Exortile** [comment]
bruh

**Comment by Sewer56** [comment]
F
